### PR TITLE
Create 2024-06-20-trainers-meeting-notes.md

### PR DESCRIPTION
**Pull request by sheraaronhurt**
---

### CODE REVIEW

**Review by jonathanwheeler01 — CHANGES_REQUESTED** [review]
Looks good - I'm assuming Jennifer approved recording/sharing the session and her presentation. Can we confirm that before approving?

**Comment by ragamouf** [comment]
I've dm'd Jennifer about permissions for sharing her recording on a) the public Trainer repo and b) promoting to the Trainers and more broadly across the Carpentries commuity.

**Comment by ragamouf** [comment]
Jennifer has provided permission to share her video on the Trainers repo, among the Trainer community and also more generally across the Carpentries community in the slack.

**Review by ragamouf — APPROVED** [review]
Jennifer provided permission to share her recording to trainer repo (public), trainer community and carpo community more broadly on the slack.

**Review by ndporter — APPROVED** [review]

**Review by ragamouf — APPROVED** [review]

**Pull request merged**
