### PR TITLE
Clarify interpret trainer certification renewal power

### PR DESCRIPTION
**Pull request by brownsarahm**
This was requested from the EC. 

TBD if this needs to be approved by the trainer community as a whole.

### CODE REVIEW

**Review by jcoliver — COMMENTED** [review]
Could we add consistency to the document to always refer to this as "Instructor Trainer Certification Renewal Procedure" (sometimes it's "process", sometimes it's just "Renewal")?

**Comment by brownsarahm** [comment]
yes! those are my error from a previous PR, I expected to fix that before it was merged and missed it.  What do we want the terminology to be? When I was updating it from agreement I wasn't sure of the right term.

**Comment by jcoliver** [comment]
Well, not "policy", that's for sure. :grin: 

"Process" seems appropriate to me.

**Comment by marklcrowe** [comment]
I think the wording should depend on what we expect to be doing - will we be reviewing all 'non-standard' submissions to decide whether or not they are sufficient for renewal, or will we be developing a conversion chart of what other activities are equivalent to the required workshop/demos/meetings combination? Or more likely, starting with the former and gradually building the latter as we get experience as to what people are nominating as their alternative contributions. 

The process document says "equivalent engagement with curriculum, trainees, or the Trainer community, **as approved by the Trainers Leadership**", so that would include both options.

Perhaps: 
* Review Trainer Certification Renewal submissions to determine which self-reported activities are "equivalent engagement" to the stated renewal requirements

**Comment by brownsarahm** [comment]
This power is what give the trainer leadership the authority to produce that other document and the powers document is a part of what get approved by larger bodies (EC and/or all trainers). So we need to phrase this to be clear, but also permissive so that we can, for example change the implementation procedure without separate approval. 

This also gets at the language matter: there is the overall [process](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html#certification-renewal-process) including "participation requirements" for automatic renewal that the whole trainer community votes on. The thing that we do on our own is currently titled the [implementation](https://github.com/carpentries/trainers/issues/167) proposal.

I've revised the PR further to reflect these comments. I made all instances of "Trainer Certification Renewal"  end in either "Process" (the whole approved document that lives in the handbook) or the "Participation Requirements" which is a list in  that document. 

Maybe for ease of reference we [add a subheading to the process in the handbook](https://github.com/carpentries/docs.carpentries.org/compare/main...brownsarahm:patch-3) (this is not a PR yet, just the compare page) 

Hopefully this is still clear enough? while remaining permissive enough to be meaningful and not require too many approving votes.

**Review by karenword — APPROVED** [review]

**Comment by marklcrowe** [comment]
Sorry, I was trying to see the latest changes but looks like I've clicked on the wrong button and 'marked it ready for review', whatever that means. All looks good to me now, can someone fix it again please if that's needed?

**Comment by brownsarahm** [comment]
I put it back to a draft (the button is at the top right near the list of reviewers) because I think we still need to decide if we want to merge this in, or if we need to hold for a trainer vote.

**Comment by karenword** [comment]
@marklcrowe I did the same thing... that button is just too tempting when you are trying to submit a review!

**Pull request merged**
